spring:
  application:
    name: ethereum-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8101

management:
  endpoints:
    web:
      exposure:
        include: "*"